### ISSUE TITLE
just test file upload。

### ISSUE THREAD

**Issue by sj279811799** [vinkdong/timing#1]
file
![default](https://user-images.githubusercontent.com/12233760/33420190-a8b8b00a-d5e8-11e7-82c9-89110c2eda53.jpeg)

**Comment by sj279811799** [comment]
file2
[事件单-2017-11-23.xlsx](https://github.com/VinkDong/TimingRequest/files/1516962/-2017-11-23.xlsx)

**Comment by sj279811799** [comment]
🌶🐔

**Comment by vinkdong** [comment]
@sj279811799 file upload doesn't support right now, It is coming soon.

**Comment by sj279811799** [comment]
do u ever seen attachment download component? like this
![image](https://user-images.githubusercontent.com/12233760/33420628-498b269c-d5ea-11e7-9dc3-c8b3cdb2fda1.png)

**Comment by sj279811799** [comment]
![image](https://user-images.githubusercontent.com/12233760/33470848-6839bb56-d6a5-11e7-83b6-538f7899a425.png)

**Comment by sj279811799** [comment]
![ac407685a8c5fb2c6a37262feedcc36c](https://user-images.githubusercontent.com/12233760/35550717-ad5e1290-05c6-11e8-9f19-2d9f30c90223.jpg)
